### ISSUE TITLE
Ocean stops generating on world generation with this installed

### ISSUE THREAD

**Issue by Agent3554** [Valks-Terraria-Mods/PlentifulOres#2]
As the title says, also add a configurable option to enable/disable certain ores/gems when generating a world, and recommended to include other gem types, Copper/Tin and Silver/Tungsten as well, basically include all gems/ores and add a config option to whitelist/blacklist ores and gems

**Comment by CyberSecAlexG** [comment]
Can confirm, this also happens to me. Can't use this at the moment.

**Comment by valkyrienyanko** [comment]
> also add a configurable option to enable/disable certain ores/gems when generating a world, and recommended to include other gem types, Copper/Tin and Silver/Tungsten as well, basically include all gems/ores and add a config option to whitelist/blacklist ores and gems

A config has been added. Setting the values all to `0` in the config will disable all ore generation.

> Ocean stops generating on world generation

This has been fixed.
